CREATE TABLE IF NOT EXISTS CAR(
    ID BIGINT NOT NULL,
    OWNERID BIGINT NOT NULL,
    DATEADDED DATE NOT NULL,
    MANUFACTURERNAME VARCHAR(64) NOT NULL,
    MODELNAME VARCHAR(64) NOT NULL,
    PRODUCTIONYEAR SMALLINT NOT NULL,
    SERIALNUMBER BIGINT UNIQUE NOT NULL,
    CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CHECKUP(
    ID BIGINT NOT NULL,
    DATETIME TIMESTAMP(0) NOT NULL,
    WORKERNAME VARCHAR(64) NOT NULL,
    PRICE FLOAT NOT NULL,
    CARID BIGINT NOT NULL,
    CONSTRAINT CHECKUP_ID PRIMARY KEY (ID),
    CONSTRAINT CHECKUP_CARID_FK FOREIGN KEY (CARID) REFERENCES CAR(ID)
);

CREATE SEQUENCE IF NOT EXISTS CAR_SEQ;

CREATE SEQUENCE IF NOT EXISTS CHECKUP_SEQ;