services:
  app:
    image: "academy/buildpack-image"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://cars-db:5432/cars-db"

  cars-db:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "cars-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=cars-db"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"

  redis-cache:
    image: "redis:6.2.4-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "cache-data:/data"

volumes:
  cars-data:
  cache-data: