services:
  cars-db:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "cars-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=cars-db"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"

volumes:
  cars-data: